### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Vickey-ZWQ** [FabianEckermann/ns-3_c-v2x#3] opened 2020-07-29 02:40 UTC
When I run the v2x_communication_example, it show me thise error and it seem the ns3-lte modle error. I am a beginner of NS-3, please help. By the way I run it on Ubuntu 20.04, the version of NS-3 is 3.30.1.

![build_error](https://user-images.githubusercontent.com/52652822/88750321-d5718c00-d187-11ea-9f84-8ca0aee90fcd.png)

**Comment by FabianEckermann** [comment] 2020-08-24 12:05
seems like a duplicate of #1

**Closed as completed by FabianEckermann** 2020-08-24 12:05 UTC
